// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Dipakai HANYA oleh `prisma migrate` / `prisma studio` dari CLI, bukan
  // oleh aplikasi saat runtime (runtime pakai driver adapter di
  // src/lib/prisma.ts). Boleh isi dengan connection string pooled Neon,
  // tapi kalau migrate gagal karena timeout/prepared statement, ganti
  // sementara ke DIRECT_URL (non-pooled) di .env.local saat migrate saja.
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
